name: "Build and push docker stage"
description: "Builds and pushes stages from a docker file"
inputs:
   stage-name:
     required: true
     description: "The name of the stage in the Docker multi-stage file."
   tag-name:
     required: true
     description: "The tag under which to publish."
   context:
     required: true
     description: "Path to the docker context."
   username:
     required: true
     description: "The username for the docker login action." 
   password:
     required: true
     description: "The password for the docker login action." 
     
runs:
  using: "composite"
  steps:      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
          
    - name: Build base image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        target: ${{ inputs.stage-name }}
        push: true
        context: ${{ inputs.context }}
        tags: ${{ inputs.tag-name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
